<<<<<<< HEAD
=======
<<<<<<< HEAD:backend/error.log
{"address":"::1","code":"ECONNREFUSED","errno":-4078,"level":"error","message":"Error connecting to PostgreSQL database: connect ECONNREFUSED ::1:5000","port":5000,"stack":"Error: connect ECONNREFUSED ::1:5000\n    at D:\\FOREXRemmitance\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\FOREXRemmitance\\forex-remittance\\backend\\database\\db.js:13:20)","syscall":"connect"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"326","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at D:\\FOREXRemmitance\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\FOREXRemmitance\\forex-remittance\\backend\\database\\db.js:13:20)"}
=======
<<<<<<< HEAD
{"code":"28P01","file":"auth.c","length":105,"level":"error","line":"329","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgress\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgress\"\n    at D:\\main project\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\main project\\forex-remittance\\backend\\database\\db.js:15:20)"}
{"code":"28P01","file":"auth.c","length":105,"level":"error","line":"329","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgress\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgress\"\n    at D:\\main project\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\main project\\forex-remittance\\backend\\database\\db.js:15:20)"}
{"code":"28P01","file":"auth.c","length":105,"level":"error","line":"329","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgress\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgress\"\n    at D:\\main project\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\main project\\forex-remittance\\backend\\database\\db.js:15:20)"}
{"code":"28P01","file":"auth.c","length":105,"level":"error","line":"329","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgress\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgress\"\n    at D:\\main project\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\main project\\forex-remittance\\backend\\database\\db.js:15:20)"}
{"code":"28P01","file":"auth.c","length":105,"level":"error","line":"329","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgress\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgress\"\n    at D:\\main project\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\main project\\forex-remittance\\backend\\database\\db.js:15:20)"}
{"address":"::1","code":"ECONNREFUSED","errno":-4078,"level":"error","message":"Error connecting to PostgreSQL database: connect ECONNREFUSED ::1:5432","port":5432,"stack":"Error: connect ECONNREFUSED ::1:5432\n    at D:\\main project\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\main project\\forex-remittance\\backend\\database\\db.js:15:20)","syscall":"connect"}
{"address":"::1","code":"ECONNREFUSED","errno":-4078,"level":"error","message":"Error connecting to PostgreSQL database: connect ECONNREFUSED ::1:5432","port":5432,"stack":"Error: connect ECONNREFUSED ::1:5432\n    at D:\\main project\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\main project\\forex-remittance\\backend\\database\\db.js:15:20)","syscall":"connect"}
{"level":"error","message":"Error connecting to PostgreSQL database: The server does not support SSL connections","stack":"Error: The server does not support SSL connections\n    at D:\\main project\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\main project\\forex-remittance\\backend\\database\\db.js:15:20)"}
{"code":"28P01","file":"auth.c","length":105,"level":"error","line":"326","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgress\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgress\"\n    at D:\\main project\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\main project\\forex-remittance\\backend\\database\\db.js:15:20)"}
{"code":"28P01","file":"auth.c","length":105,"level":"error","line":"326","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgress\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgress\"\n    at D:\\main project\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\main project\\forex-remittance\\backend\\database\\db.js:14:20)"}
{"code":"28P01","file":"auth.c","length":105,"level":"error","line":"326","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgress\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgress\"\n    at D:\\main project\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\main project\\forex-remittance\\backend\\database\\db.js:13:20)"}
{"level":"error","message":"Error connecting to PostgreSQL database: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string","stack":"Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string\n    at D:\\main project\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\main project\\forex-remittance\\backend\\database\\db.js:13:20)"}
{"code":"28P01","file":"auth.c","length":105,"level":"error","line":"326","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgress\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgress\"\n    at D:\\main project\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\main project\\forex-remittance\\backend\\database\\db.js:13:20)"}
{"code":"28P01","file":"auth.c","length":105,"level":"error","line":"326","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgress\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgress\"\n    at D:\\main project\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\main project\\forex-remittance\\backend\\database\\db.js:13:20)"}
{"address":"::1","code":"ECONNREFUSED","errno":-4078,"level":"error","message":"Error connecting to PostgreSQL database: connect ECONNREFUSED ::1:5432","port":5432,"stack":"Error: connect ECONNREFUSED ::1:5432\n    at D:\\main project\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\main project\\forex-remittance\\backend\\database\\db.js:13:20)","syscall":"connect"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"326","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at D:\\main project\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\main project\\forex-remittance\\backend\\database\\db.js:13:20)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"326","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at D:\\main project\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\main project\\forex-remittance\\backend\\database\\db.js:13:20)"}
=======
<<<<<<< HEAD
{"level":"error","message":"Error connecting to PostgreSQL database:"}
{"level":"error","message":"Error connecting to PostgreSQL database:"}
{"level":"error","message":"Error connecting to PostgreSQL database:"}
{"level":"error","message":"Error signing up user: Username already exists","stack":"Error: Username already exists\n    at User.checkUserExistence (D:\\forex-remittance\\forex-remittance\\backend\\models\\User.js:50:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async UserController.signUp (D:\\forex-remittance\\forex-remittance\\backend\\controllers\\UserController.js:13:7)"}
{"level":"error","message":"Error signing up user: Username already exists","stack":"Error: Username already exists\n    at User.checkUserExistence (D:\\forex-remittance\\forex-remittance\\backend\\models\\User.js:50:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async UserController.signUp (D:\\forex-remittance\\forex-remittance\\backend\\controllers\\UserController.js:13:7)"}
<<<<<<< HEAD
{"code":"ECONNREFUSED","level":"error","message":"Error connecting to PostgreSQL database:","stack":"AggregateError\n    at D:\\Forex\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\Forex\\forex-remittance\\backend\\database\\db.js:14:20)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"326","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at D:\\Forex\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\Forex\\forex-remittance\\backend\\database\\db.js:14:20)"}
=======
{"level":"error","message":"Error connecting to PostgreSQL database:"}
{"level":"error","message":"Error during login: Error finding user: connect ECONNREFUSED ::1:5432","stack":"Error: Error finding user: connect ECONNREFUSED ::1:5432\n    at findUser (D:\\main project\\forex-remittance\\backend\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\main project\\forex-remittance\\backend\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error during login: Error finding user: connect ECONNREFUSED ::1:5432","stack":"Error: Error finding user: connect ECONNREFUSED ::1:5432\n    at findUser (D:\\main project\\forex-remittance\\backend\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\main project\\forex-remittance\\backend\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error during login: Error finding user: connect ECONNREFUSED ::1:5432","stack":"Error: Error finding user: connect ECONNREFUSED ::1:5432\n    at findUser (D:\\main project\\forex-remittance\\backend\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\main project\\forex-remittance\\backend\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error during login: Error finding user: connect ECONNREFUSED ::1:5432","stack":"Error: Error finding user: connect ECONNREFUSED ::1:5432\n    at findUser (D:\\main project\\forex-remittance\\backend\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\main project\\forex-remittance\\backend\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error during login: Error finding user: connect ECONNREFUSED ::1:5432","stack":"Error: Error finding user: connect ECONNREFUSED ::1:5432\n    at findUser (D:\\main project\\forex-remittance\\backend\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\main project\\forex-remittance\\backend\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error connecting to PostgreSQL database:"}
{"level":"error","message":"Error during login: Error finding user: connect ECONNREFUSED ::1:5432","stack":"Error: Error finding user: connect ECONNREFUSED ::1:5432\n    at findUser (D:\\main project\\forex-remittance\\backend\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\main project\\forex-remittance\\backend\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error during login: Error finding user: connect ECONNREFUSED ::1:5432","stack":"Error: Error finding user: connect ECONNREFUSED ::1:5432\n    at findUser (D:\\main project\\forex-remittance\\backend\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\main project\\forex-remittance\\backend\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error during login: Error finding user: connect ECONNREFUSED ::1:5432","stack":"Error: Error finding user: connect ECONNREFUSED ::1:5432\n    at findUser (D:\\main project\\forex-remittance\\backend\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\main project\\forex-remittance\\backend\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error during login: Error finding user: connect ECONNREFUSED ::1:5432","stack":"Error: Error finding user: connect ECONNREFUSED ::1:5432\n    at findUser (D:\\main project\\forex-remittance\\backend\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\main project\\forex-remittance\\backend\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error during login: Error finding user: connect ECONNREFUSED ::1:5432","stack":"Error: Error finding user: connect ECONNREFUSED ::1:5432\n    at findUser (D:\\main project\\forex-remittance\\backend\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\main project\\forex-remittance\\backend\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error during login: Error finding user: connect ECONNREFUSED ::1:5432","stack":"Error: Error finding user: connect ECONNREFUSED ::1:5432\n    at findUser (D:\\main project\\forex-remittance\\backend\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\main project\\forex-remittance\\backend\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error during login: Error finding user: connect ECONNREFUSED ::1:5432","stack":"Error: Error finding user: connect ECONNREFUSED ::1:5432\n    at findUser (D:\\main project\\forex-remittance\\backend\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\main project\\forex-remittance\\backend\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error during login: Error finding user: connect ECONNREFUSED ::1:5432","stack":"Error: Error finding user: connect ECONNREFUSED ::1:5432\n    at findUser (D:\\main project\\forex-remittance\\backend\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\main project\\forex-remittance\\backend\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error during login: Error finding user: connect ECONNREFUSED ::1:5432","stack":"Error: Error finding user: connect ECONNREFUSED ::1:5432\n    at findUser (D:\\main project\\forex-remittance\\backend\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\main project\\forex-remittance\\backend\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error during login: Error finding user: connect ECONNREFUSED ::1:5432","stack":"Error: Error finding user: connect ECONNREFUSED ::1:5432\n    at findUser (D:\\main project\\forex-remittance\\backend\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\main project\\forex-remittance\\backend\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error during login: Error finding user: connect ECONNREFUSED ::1:5432","stack":"Error: Error finding user: connect ECONNREFUSED ::1:5432\n    at findUser (D:\\main project\\forex-remittance\\backend\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\main project\\forex-remittance\\backend\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error during login: Error finding user: connect ECONNREFUSED ::1:5432","stack":"Error: Error finding user: connect ECONNREFUSED ::1:5432\n    at findUser (D:\\main project\\forex-remittance\\backend\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\main project\\forex-remittance\\backend\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error connecting to PostgreSQL database:"}
{"level":"error","message":"Error connecting to PostgreSQL database:"}
{"level":"error","message":"Error during login: Error finding user: connect ECONNREFUSED ::1:5432","stack":"Error: Error finding user: connect ECONNREFUSED ::1:5432\n    at findUser (D:\\main project\\forex-remittance\\backend\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\main project\\forex-remittance\\backend\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error during login: Error finding user: connect ECONNREFUSED ::1:5432","stack":"Error: Error finding user: connect ECONNREFUSED ::1:5432\n    at findUser (D:\\main project\\forex-remittance\\backend\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\main project\\forex-remittance\\backend\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error during login: Error finding user: connect ECONNREFUSED ::1:5432","stack":"Error: Error finding user: connect ECONNREFUSED ::1:5432\n    at findUser (D:\\main project\\forex-remittance\\backend\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\main project\\forex-remittance\\backend\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error connecting to PostgreSQL database:"}
{"level":"error","message":"Error during login: Error finding user: connect ECONNREFUSED ::1:5432","stack":"Error: Error finding user: connect ECONNREFUSED ::1:5432\n    at findUser (D:\\main project\\forex-remittance\\backend\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\main project\\forex-remittance\\backend\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error connecting to PostgreSQL database:"}
<<<<<<< HEAD
{"level":"error","message":"Error connecting to PostgreSQL database:"}
=======
>>>>>>> 470d98badd1cdc4ac36733cb7cb345ee06ce10e1
>>>>>>> 6de4798e7570b655ae873db4d96a7a20accef894
=======
>>>>>>> 4ccf5a094f3ccefd7614bbd62b760497a8503bc3
>>>>>>> 3dcc6dc3c2cf8f957bd3ba16691fd77766070ea7
{"level":"error","message":"Error connecting to PostgreSQL database: Connection terminated unexpectedly","stack":"Error: Connection terminated unexpectedly\n    at D:\\for-x\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\for-x\\forex-remittance\\backend\\database\\db.js:13:20)"}
{"level":"error","message":"Error connecting to PostgreSQL database: Connection terminated unexpectedly","stack":"Error: Connection terminated unexpectedly\n    at D:\\for-x\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\for-x\\forex-remittance\\backend\\database\\db.js:13:20)"}
{"level":"error","message":"Error connecting to PostgreSQL database: Connection terminated unexpectedly","stack":"Error: Connection terminated unexpectedly\n    at D:\\for-x\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\for-x\\forex-remittance\\backend\\database\\db.js:13:20)"}
{"address":"::1","code":"ECONNREFUSED","errno":-4078,"level":"error","message":"Error connecting to PostgreSQL database: connect ECONNREFUSED ::1:5","port":5,"stack":"Error: connect ECONNREFUSED ::1:5\n    at D:\\for-x\\forex-remittance\\backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\for-x\\forex-remittance\\backend\\database\\db.js:13:20)","syscall":"connect"}
{"address":"::1","code":"ECONNREFUSED","errno":-4078,"level":"error","message":"Error connecting to PostgreSQL database: connect ECONNREFUSED ::1:5432","port":5432,"stack":"Error: connect ECONNREFUSED ::1:5432\n    at D:\\Forex_Remittance\\forex-remittance\\backend1\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\Forex_Remittance\\forex-remittance\\backend1\\database\\db.js:13:20)","syscall":"connect"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"326","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at D:\\Forex_Remittance\\forex-remittance\\backend1\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\Forex_Remittance\\forex-remittance\\backend1\\database\\db.js:13:20)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"326","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at D:\\Forex_Remittance\\forex-remittance\\backend1\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\Forex_Remittance\\forex-remittance\\backend1\\database\\db.js:13:20)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"326","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at D:\\Forex_Remittance\\forex-remittance\\backend1\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\Forex_Remittance\\forex-remittance\\backend1\\database\\db.js:13:20)"}
>>>>>>> ce680cacfd6a4824adb18ee4065307af3b91fbc7:backend1/error.log
{"code":"28P01","file":"auth.c","length":103,"level":"error","line":"329","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgre\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgre\"\n    at D:\\Forex_Remittance\\forex-remittance\\backend1\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\Forex_Remittance\\forex-remittance\\backend1\\database\\db.js:15:20)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"329","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at D:\\Forex_Remittance\\forex-remittance\\backend1\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\Forex_Remittance\\forex-remittance\\backend1\\database\\db.js:15:20)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"329","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at D:\\Forex_Remittance\\forex-remittance\\backend1\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\Forex_Remittance\\forex-remittance\\backend1\\database\\db.js:15:20)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"329","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at D:\\Forex_Remittance\\forex-remittance\\backend1\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\Forex_Remittance\\forex-remittance\\backend1\\database\\db.js:15:20)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"329","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at D:\\Forex_Remittance\\forex-remittance\\backend1\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\Forex_Remittance\\forex-remittance\\backend1\\database\\db.js:15:20)"}
{"address":"::1","code":"ECONNREFUSED","errno":-4078,"level":"error","message":"Error connecting to PostgreSQL database: connect ECONNREFUSED ::1:5432","port":5432,"stack":"Error: connect ECONNREFUSED ::1:5432\n    at D:\\Forex_Remittance\\forex-remittance\\backend1\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\Forex_Remittance\\forex-remittance\\backend1\\database\\db.js:15:20)","syscall":"connect"}
{"level":"error","message":"Error connecting to PostgreSQL database: The server does not support SSL connections","stack":"Error: The server does not support SSL connections\n    at D:\\Forex_Remittance\\forex-remittance\\backend1\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\Forex_Remittance\\forex-remittance\\backend1\\database\\db.js:15:20)"}
{"code":"28P01","file":"auth.c","length":104,"level":"error","line":"326","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgres\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgres\"\n    at D:\\Forex_Remittance\\forex-remittance\\backend1\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\Forex_Remittance\\forex-remittance\\backend1\\database\\db.js:15:20)"}
{"code":"28P01","file":"auth.c","length":103,"level":"error","line":"326","message":"Error connecting to PostgreSQL database: password authentication failed for user \"postgre\"","name":"error","routine":"auth_failed","severity":"FATAL","stack":"error: password authentication failed for user \"postgre\"\n    at D:\\Forex_Remittance\\forex-remittance\\backend1\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async connectToDatabase (D:\\Forex_Remittance\\forex-remittance\\backend1\\database\\db.js:15:20)"}
>>>>>>> 59d62088dc5e49000f47bc01c2aad6c668286d44
{"level":"error","message":"Error during login: Error finding user: getaddrinfo ENOTFOUND dpg-clkrmpsjtl8s73f17fq0-a.oregon-postgres.render.com","stack":"Error: Error finding user: getaddrinfo ENOTFOUND dpg-clkrmpsjtl8s73f17fq0-a.oregon-postgres.render.com\n    at findUser (D:\\FOREXRemmitance\\forex-remittance\\backend1\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\FOREXRemmitance\\forex-remittance\\backend1\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error during login: Error finding user: getaddrinfo ENOTFOUND dpg-clkrmpsjtl8s73f17fq0-a.oregon-postgres.render.com","stack":"Error: Error finding user: getaddrinfo ENOTFOUND dpg-clkrmpsjtl8s73f17fq0-a.oregon-postgres.render.com\n    at findUser (D:\\FOREXRemmitance\\forex-remittance\\backend1\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\FOREXRemmitance\\forex-remittance\\backend1\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error during login: Error finding user: getaddrinfo ENOTFOUND dpg-clkrmpsjtl8s73f17fq0-a.oregon-postgres.render.com","stack":"Error: Error finding user: getaddrinfo ENOTFOUND dpg-clkrmpsjtl8s73f17fq0-a.oregon-postgres.render.com\n    at findUser (D:\\FOREXRemmitance\\forex-remittance\\backend1\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\FOREXRemmitance\\forex-remittance\\backend1\\controllers\\LoginController.js:7:18)"}
{"level":"error","message":"Error during login: Error finding user: getaddrinfo ENOTFOUND dpg-clkrmpsjtl8s73f17fq0-a.oregon-postgres.render.com","stack":"Error: Error finding user: getaddrinfo ENOTFOUND dpg-clkrmpsjtl8s73f17fq0-a.oregon-postgres.render.com\n    at findUser (D:\\FOREXRemmitance\\forex-remittance\\backend1\\models\\userModel.js:8:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async login (D:\\FOREXRemmitance\\forex-remittance\\backend1\\controllers\\LoginController.js:7:18)"}
